
SOURCES += $$PWD/boards/Board.cpp \
    $$PWD/boards/BoardBase.cpp \
    $$PWD/game/Game.cpp \
    $$PWD/game/GameState.cpp \
    $$PWD/models/CellDataObject.cpp \
    $$PWD/states/BishopState.cpp \
    $$PWD/states/KingState.cpp \
    $$PWD/states/KnightState.cpp \
    $$PWD/states/NoneState.cpp \
    $$PWD/states/PawnState.cpp \
    $$PWD/states/PieceState.cpp \
    $$PWD/states/QueenState.cpp \
    $$PWD/states/RookState.cpp \
    $$PWD/Constants.cpp \
    $$PWD/boards/OnePieceBoard.cpp \
    $$PWD/controllers/BoardController.cpp \
    $$PWD/boards/FreeMovePolicy.cpp \
    $$PWD/boards/MovePolicy.cpp \
    $$PWD/boards/RegularChessMovePolicy.cpp \
    $$PWD/boards/Move.cpp \
    $$PWD/boards/OneMoveAheadBoard.cpp \
    $$PWD/Utils.cpp \
    $$PWD/controllers/Controller.cpp \
    $$PWD/models/MoveModel.cpp \
    $$PWD/controllers/MoveListController.cpp \
    $$PWD/controllers/GameMenuController.cpp \
    $$PWD/controllers/board_controller/BoardControllerState.cpp \
    $$PWD/controllers/board_controller/ClientNetworkGameBoardControllerState.cpp \
    $$PWD/controllers/board_controller/LocalGameBoardControllerState.cpp \
    $$PWD/controllers/board_controller/NetworkGameBoardControllerState.cpp \
    $$PWD/controllers/board_controller/PlayerMockBoardControllerState.cpp \
    $$PWD/controllers/board_controller/ServerNetworkGameBoardControllerState.cpp \
    $$PWD/controllers/AlertMessageController.cpp

HEADERS += $$PWD/boards/Board.h \
    $$PWD/boards/BoardBase.h \
    $$PWD/game/Game.h \
    $$PWD/game/GameState.h \
    $$PWD/models/CellDataObject.h \
    $$PWD/states/BishopState.h \
    $$PWD/states/KingState.h \
    $$PWD/states/KnightState.h \
    $$PWD/states/NoneState.h \
    $$PWD/states/PawnState.h \
    $$PWD/states/PieceState.h \
    $$PWD/states/QueenState.h \
    $$PWD/states/RookState.h \
    $$PWD/Constants.h \
    $$PWD/Enums.h \
    $$PWD/_BoardCellIndicies_.h \
    $$PWD/boards/OnePieceBoard.h \
    $$PWD/controllers/BoardController.h \
    $$PWD/boards/FreeMovePolicy.h \
    $$PWD/boards/MovePolicy.h \
    $$PWD/boards/RegularChessMovePolicy.h \
    $$PWD/boards/Move.h \
    $$PWD/boards/OneMoveAheadBoard.h \
    $$PWD/Utils.h \
    $$PWD/controllers/Controller.h \
    $$PWD/models/MoveModel.h \
    $$PWD/controllers/MoveListController.h \
    $$PWD/controllers/GameMenuController.h \
    $$PWD/controllers/board_controller/BoardControllerState.h \
    $$PWD/controllers/board_controller/LocalGameBoardControllerState.h \
    $$PWD/controllers/board_controller/NetworkGameBoardControllerState.h \
    $$PWD/controllers/board_controller/PlayerMockBoardControllerState.h \
    $$PWD/controllers/board_controller/ServerNetworkGameBoardControllerState.h \
    $$PWD/controllers/board_controller/ClientNetworkGameBoardControllerState.h \
    $$PWD/controllers/AlertMessageController.h
